// Generated by CoffeeScript 1.4.0
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  (Project.Pages.Listing = function() {
    var bumpboxDependencies, bumpboxes, elements, fade, listingBumpboxes, topBumpbox;
    elements = [$('#navigation_left'), $('#navigation_top'), $('#logo'), $('#search'), $('#header'), $('#content')];
    topBumpbox = Project.Pages.Bumpbox(elements);
    fade = topBumpbox.fade;
    bumpboxes = pageData.listing_bumpboxes;
    bumpboxDependencies = {
      listing_inquire: Project.Modules.inquire_controller
    };
    return (listingBumpboxes = function() {
      var bumpbox, containers, contentModules, inquireAnimation, listeners, modules, _i, _len;
      listeners = {};
      containers = {};
      modules = {};
      contentModules = {};
      for (_i = 0, _len = bumpboxes.length; _i < _len; _i++) {
        bumpbox = bumpboxes[_i];
        listeners[bumpbox] = $("#navigation_left li[data-link=\"" + bumpbox + "\"]");
        containers[bumpbox] = $(".bumpbox." + bumpbox);
        modules[bumpbox] = new Project.Modules.bumpbox(listeners[bumpbox], containers[bumpbox]);
        modules[bumpbox]['config']['in_callback'] = fade.fadeOut;
        modules[bumpbox]['config']['out_callback'] = fade.fadeIn;
        if (bumpboxDependencies[bumpbox]) {
          modules[bumpbox] = new bumpboxDependencies[bumpbox](listeners[bumpbox], containers[bumpbox]);
        }
      }
      if (__indexOf.call(bumpboxes, "listing_inquire") >= 0) {
        inquireAnimation = new Project.Modules.form_animation(containers["listing_inquire"]);
      }
      return listeners['listing_inquire'].trigger("click");
    })();
  })();

}).call(this);
