// Generated by CoffeeScript 1.4.0
(function() {

  (Project.Pages.Property = function() {
    var elements;
    elements = [$('#navigation_browse'), $('#navigation_top'), $('#logo'), $('#search'), $('#header')];
    return Project.Pages.Bumpbox(elements);
  })();

}).call(this);
