// Generated by CoffeeScript 1.6.2
(function() {
  (Project.Pages.Vacancy = function() {
    var elements, topBumpbox;

    elements = [$('#navigation_left'), $('#navigation_top'), $('#logo'), $('#search'), $('#header'), $('#page_content')];
    return topBumpbox = Project.Pages.Bumpbox(elements);
  })();

}).call(this);
