// Generated by CoffeeScript 1.6.3
(function() {
  (Project.Pages.Vacancy = function() {
    var bumpbox, bumpbox_init, elements, fade,
      _this = this;
    elements = [$('#navigation_left'), $('#navigation_top'), $('#logo'), $('#search'), $('#header'), $('#page_container'), $('#page_content')];
    bumpbox = Project.Pages.Bumpbox(elements);
    fade = bumpbox.fade;
    return (bumpbox_init = function() {
      var bumpbox_controllers, bumpbox_modules, controller, init, name, _results;
      bumpbox_controllers = {
        "about": new Project.Modules.bumpbox($('#navigation_left li.about'), $('.bumpbox.about')),
        "team": new Project.Modules.bumpbox($('#navigation_left li.team'), $('.bumpbox.team')),
        "services": new Project.Modules.bumpbox($('#navigation_left li.services'), $('.bumpbox.services'))
      };
      bumpbox_modules = {
        "team": new Project.Modules.thumbnail_controller($('.bumpbox.team > .thumbnails > ul'), $('.bumpbox.team > .content'), 0),
        "services": new Project.Modules.thumbnail_controller($('.bumpbox.services > .thumbnails > ul'), $('.bumpbox.services > .content'), 0),
        "about": new Project.Modules.thumbnail_controller($('.bumpbox.about > .thumbnails > ul'), $('.bumpbox.about > .content'), 0)
      };
      init = function(controller) {
        controller['config']['in_callback'] = fade.fadeOut;
        return controller['config']['out_callback'] = fade.fadeIn;
      };
      _results = [];
      for (name in bumpbox_controllers) {
        controller = bumpbox_controllers[name];
        _results.push(init(controller));
      }
      return _results;
    })();
  })();

}).call(this);
