// Generated by CoffeeScript 1.6.3
(function() {
  var _this = this;

  Project.Modules.general_maps = function(thumbnails, container) {
    var changeTrigger, data, mapInit, maps;
    _this.thumbnails = thumbnails;
    data = pageData.general_maps;
    maps = {};
    mapInit = function(id) {
      var infowindows, map, markers, options, property, _container, _data, _i, _len, _ref, _results;
      _data = data[id];
      _container = container.find("div[data-id='" + id + "'] > div").get(0);
      options = {
        center: new google.maps.LatLng(_data.center.latitude, _data.center.longitude),
        zoom: 11,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      map = new google.maps.Map(_container, options);
      markers = [];
      infowindows = [];
      _ref = _data.properties;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        property = _ref[_i];
        _results.push((function() {
          var infowindow, marker;
          infowindow = new google.maps.InfoWindow({
            content: property.infobox
          });
          marker = new google.maps.Marker({
            map: map,
            draggable: false,
            visible: true,
            position: new google.maps.LatLng(property.coordinates.latitude, property.coordinates.longitude)
          });
          markers.push(marker);
          infowindows.push(infowindow);
          return google.maps.event.addListener(marker, "click", function() {
            var otherInfowindow, _j, _len1;
            for (_j = 0, _len1 = infowindows.length; _j < _len1; _j++) {
              otherInfowindow = infowindows[_j];
              otherInfowindow.close();
            }
            return infowindow.open(map, marker);
          });
        })());
      }
      return _results;
    };
    changeTrigger = function(id) {
      return maps[id] != null ? maps[id] : maps[id] = mapInit(id);
    };
    return {
      changeTrigger: changeTrigger
    };
  };

}).call(this);
