// Generated by CoffeeScript 1.6.2
(function() {
  Project.Modules.inquire_controller = function(listener, container) {
    var config, data;

    config = {
      form: container.find("form"),
      destination: container.find("form").attr("destination"),
      messageContainer: container.find(".message"),
      submitButton: container.find("button[type='submit']"),
      serverData: pageData.listingInquireData,
      animationTime: 1000,
      messageHold: 5000,
      success: function(response) {
        config.messageContainer.html(response.message);
        return config.form.fadeOut(config.animationTime, function() {
          return config.messageContainer.fadeIn(config.animationTime, function() {
            var timer;

            timer = function() {
              $('#bumpbox_out_trigger').trigger("click");
              return config.messageContainer.html(response.final_message);
            };
            return setTimeout(timer, config.messageHold);
          });
        });
      },
      error: function(response) {
        config.messageContainer.html(response.message);
        return config.messageContainer.fadeIn(config.animationTime, function() {
          var timer;

          timer = function() {
            return config.messageContainer.fadeOut(config.animationTime);
          };
          return setTimeout(timer, config.messageHold);
        });
      }
    };
    data = function() {
      var _data;

      _data = config.serverData;
      _data.message = config.form.find("textarea").attr("value");
      _data.email = config.form.find("input").attr("value");
      return _data;
    };
    return config.submitButton.click(function() {
      $.ajax({
        url: config.destination,
        data: data(),
        type: 'POST',
        dataType: 'json',
        error: function(response) {
          return console.log(response);
        },
        success: function(response) {
          if (response.status) {
            return config.success(response);
          } else {
            return config.error(response);
          }
        }
      });
      return false;
    });
  };

}).call(this);
