// Generated by CoffeeScript 1.4.0
(function() {

  Project.Modules.inquire_controller = function(listener, container) {
    var config, data;
    config = {
      form: container.children("form"),
      destination: container.children("form").attr("destination"),
      messageContainer: container.children("form").attr("destination"),
      submitButton: container.find("button[type='submit']"),
      serverData: pageData.listingInquireData,
      animationTime: 1000,
      messageHold: 5000,
      success: function(response) {
        config.messageContainer.html(response.message);
        return config.form.fadeOut(config.animationTime, function() {
          return config.messageContainer.fadeIn(config.animationTime, function() {
            var timer;
            timer = function() {
              return config.messageContainer.fadeOut(config.animationTime);
            };
            return setTimeout(timer, config.messageHold);
          });
        });
      },
      failure: function(response) {
        config.messageContainer.html(response.message);
        return config.messageContainer.fadeIn(config.animationTime, function() {
          var timer;
          timer = function() {
            return config.messageContainer.fadeOut(config.animationTime);
          };
          return setTimeout(time, config.messageHold);
        });
      }
    };
    data = function() {
      var _data;
      _data = config.serverData;
      _data.message = config.form.find("textarea").html();
      _data.email = config.form.find("input[name='email']");
      return _data;
    };
    return config.submitButton.click(function() {
      data = data();
      console.log(data);
      return false;
    });
  };

}).call(this);
