// Generated by CoffeeScript 1.4.0
(function() {
  var Listing_directions;

  Listing_directions = (function() {

    function Listing_directions() {
      alert("hello from constructor");
    }

    Listing_directions.prototype.test = Listing_directions;

    return Listing_directions;

  })();

}).call(this);
