// Generated by CoffeeScript 1.4.0
(function() {

  Project.Modules.listing_map_controller = function() {
    var walkscore_init;
    ({
      change_trigger: function(id) {
        return console.log(id);
      }
    });
    return (walkscore_init = function() {
      var data, leftElement, map, mapElement;
      data = pageData.listing_map.walkscore;
      leftElement = $('.bumpbox.listing_map > div.content > div[data-id="walkscore" > div:first-child');
      mapElement = $('.bumpbox.listing_map > div.content > div[data-id="walkscore"] > div:nth-child(2)');
      console.log(data.boundary);
      return map = new Project.Modules.walkscore_map(mapElement[0], data);
    })();
  };

}).call(this);
