// Generated by CoffeeScript 1.4.0
(function() {
  var _this = this;

  Project.Modules.listing_directions = function(form, container, data, map) {
    var getDirections, update;
    _this.form = form;
    _this.container = container;
    _this.data = data;
    _this.map = map;
    _this.elements = {
      destination: _this.form.find("input[name='destination']"),
      origin: _this.form.find("input[name='origin']"),
      submit: _this.form.find("[type='submit']")
    };
    update = function(data) {};
    getDirections = function(origin, destination) {
      return $.ajax({
        type: "get",
        url: "http://maps.googleapis.com/maps/api/directions/json?origin=" + (encodeURI(origin)) + "&destination=" + (encodeURI(destination)) + "&sensor=false",
        failure: function(response) {
          return console.log("no elements found put message here!");
        },
        success: function(response) {
          return update(response.routes[0].legs);
        }
      });
    };
    return _this.elements.submit.click(function() {
      return getDirections(_this.elements.origin.attr("value"), _this.elements.destination.attr("value"));
    });
  };

}).call(this);
