// Generated by CoffeeScript 1.6.3
/*
	Initialize a temporary bumpbox listener that will pop up a bigger box that the image can be displayed in etc
*/


(function() {
  Project.Pages.ListingImage = function(listener, bumpbox) {
    var animationDuration, exit, hide, image, show;
    image = bumpbox.find(".content > img");
    exit = bumpbox.find(".exit");
    animationDuration = 200;
    hide = function() {
      return bumpbox.fadeOut(animationDuration);
    };
    show = function() {
      var img;
      img = listener.find("div:visible > img").attr("src");
      image.attr("src", img);
      return bumpbox.fadeIn(animationDuration);
    };
    exit.click(function() {
      return hide();
    });
    return listener.click(function() {
      return show();
    });
  };

}).call(this);
