// Generated by CoffeeScript 1.4.0
(function() {
  var _this = this;

  Project.Modules.places_controller = function(form_container, map, data) {
    var error, getPlaces, success;
    _this.map = map;
    _this.data = data;
    _this.searchInput = form_container.find("input[name='search']");
    _this.typeInput = form_container.find("select[name='type']");
    _this.searchSubmit = form_container.find("[type='submit']");
    error = function(value) {};
    success = function() {};
    getPlaces = function(value, type) {};
    return _this.searchSubmit.click(function() {
      var status;
      return status = getPlaces(_this.searchInput.attr("value"), _this.typeInput.attr("value"));
    });
  };

}).call(this);
