// Generated by CoffeeScript 1.4.0
(function() {
  var _this = this;

  Project.Modules.places_controller = function(form_container, map, data) {
    var error, getPlaces, success;
    _this.map = map;
    _this.data = data;
    _this.searchInput = form_container.find("input[name='search']");
    _this.searchSubmit = form_container.find("[type='submit']");
    error = function(value) {};
    success = function() {};
    (getPlaces = function() {
      console.log(_this.data);
      return console.log(url);
    })();
    return _this.searchSubmit.click(function() {
      return alert(_this.searchInput.attr("value"));
    });
  };

}).call(this);
