// Generated by CoffeeScript 1.6.3
(function() {
  Project.Modules.Slideshow_loader = function(images, container, template) {
    var html, image, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = images.length; _i < _len; _i++) {
      image = images[_i];
      html = template(image);
      _results.push(container.append(html));
    }
    return _results;
  };

}).call(this);
