// Generated by CoffeeScript 1.4.0
(function() {

  Project.Modules.walkscore_map = function(container, data) {
    var boundsInit, mapInit,
      _this = this;
    this.container = container;
    this.data = data;
    (mapInit = function() {
      _this.center = {
        latitude: parseFloat(_this.data.center.latitude),
        longitude: parseFloat(_this.data.center.longitude)
      };
      _this.boundary = parseFloat(_this.data.boundary);
      _this.options = {
        center: new google.maps.LatLng(_this.center.latitude, _this.center.longitude),
        zoom: 14,
        mapTypeId: google.maps.MapTypeId.SATELLITE
      };
      return _this.map = new google.maps.Map(_this.container, _this.options);
    })();
    return (boundsInit = function() {
      var createMarker, element, options;
      createMarker = function(point) {
        var options;
        options = {
          position: point,
          draggable: true,
          map: _this.map
        };
        return _this.centerMarker = new google.maps.Marker(options);
      };
      _this.rectCoordinates = [];
      _this.rectCoordinates[0] = new google.maps.LatLng(_this.center.latitude + _this.boundary, _this.center.longitude - _this.boundary);
      _this.rectCoordinates[1] = new google.maps.LatLng(_this.center.latitude + _this.boundary, _this.center.longitude + _this.boundary);
      _this.rectCoordinates[3] = new google.maps.LatLng(_this.center.latitude - _this.boundary, _this.center.longitude - _this.boundary);
      _this.rectCoordinates[2] = new google.maps.LatLng(_this.center.latitude - _this.boundary, _this.center.longitude + _this.boundary);
      _this.boundMarkers = (function() {
        var _i, _len, _ref, _results;
        _ref = this.rectCoordinates;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          element = _ref[_i];
          _results.push(createMarker(element));
        }
        return _results;
      }).call(_this);
      options = {
        paths: _this.rectCoordinates,
        strokeColor: "#FF0000",
        fillColor: "#FF0000",
        fillOpacity: 0.35,
        strokeOpacity: 0.35,
        strokeWeight: 2
      };
      _this.rect = new google.maps.Polygon(options);
      return _this.rect.setMap(_this.map);
    })();
  };

}).call(this);
