// Generated by CoffeeScript 1.4.0
(function() {

  Project.Modules.walkscore_map = function(container, center, triangle) {
    var options;
    return options = {
      center: new google.maps.LatLng(center.latitude, center.longitude),
      zoom: 8,
      mapTypeId: google.maps.Map
    };
  };

}).call(this);
