// Generated by CoffeeScript 1.6.3
(function() {
  var config;

  config = {
    paths: {
      angular: "/resources/javascript/resources/angular.min",
      jquery: "/resources/javascript/resources/jquery"
    }
  };

  require.config(config);

  require(["angular"], function($) {
    return alert("HELLO WORLD");
  });

}).call(this);
