// Generated by CoffeeScript 1.6.2
(function() {
  var config;

  config = {
    paths: {
      angular: "/resources/javascript/resources/angular.min",
      jquery: "/resources/javascript/resources/jquery"
    }
  };

  require.config(config);

  require(["angular"], function($) {});

}).call(this);
